# -*- coding: utf-8 -*-
"""Tryblock_error.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hXRn0v24NM3I6NXiLrIXordIORJ4NsTf
"""

a= 10/0
print(a)

"""**TRY BLOCK IN PYTHON**"""

#try block error
try:
  a=10/0
except Exception as e:
  print(e)

#else block

try:
  a=10/6
except Exception as e:
  print(e)
else:
  print("The Value is :",a)

#finally
try:
    a=10/3
except Exception as e:
  print(e)
else:
  print("The Value is :",a)
finally:
  print("thank you")



